src/lib.rs
tests/test_inlining.rs

Improve performance

---

CHANGELOG.md
src/lib.rs
tests/test_inlining.rs

fix: Ignore @media queries

---

CHANGELOG.md
src/lib.rs
tests/test_inlining.rs

feat: Option to remove "style" tags

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.toml
python/CHANGELOG.md
python/README.rst
python/src/lib.rs
src/error.rs
src/lib.rs
tests/external.css
tests/server.py
tests/test_inlining.rs

feat: Loading external stylesheets

---

CHANGELOG.md
Cargo.toml
README.md
python/.gitignore
python/Cargo.toml
src/main.rs

feat: Command Line Interface

---

.github/workflows/build.yml
wasm/.gitignore
wasm/Cargo.toml
wasm/package.json
wasm/src/lib.rs
wasm/tests-ts/css_inline.spec.ts
wasm/tsconfig.json

chore: Add Rust & TypeScript tests for WASM crate

---

.github/workflows/rust-release.yml

Add Github Action for Rust release

---

.github/workflows/wasm-release.yml

Add release job for WASM

---

CHANGELOG.md
README.md
src/lib.rs
tests/test_inlining.rs

feat: `CSSInliner::options()` that implements the Builder pattern

---

wasm/Cargo.toml
wasm/src/lib.rs

Resolves #66 
Total size change: -453110 bytes

WASM size optimization

---

CHANGELOG.md
benches/inliner.rs
python/Cargo.toml
python/benches/bench.py
src/error.rs

Minor tweaks

---

python/Cargo.toml

As a temporary solution to have #87 merged

chore: Constraint pyo3 version

---

src/error.rs
src/lib.rs

Closes #76 
God bless the rust compiler, I just had to follow the error messages until it compiled. :)

Add usage of Cow for parse error text

---

CHANGELOG.md
src/main.rs

fix: Wrong inlined file prefix in CLI

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/python/README.rst
bindings/wasm/CHANGELOG.md
css-inline/src/lib.rs
css-inline/src/parser.rs
css-inline/tests/test_inlining.rs

fix: Ignored selectors' priorities

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/wasm/CHANGELOG.md
css-inline/src/lib.rs
css-inline/tests/test_inlining.rs

fix: Incorrect overriding of existing 'style' attribute values

---

css-inline/tests/test_inlining.rs
css-inline/tests/test_selectors.rs
css-inline/tests/utils.rs

Most of the important ones
Closes #117

Port tests from pynliner

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/wasm/CHANGELOG.md
css-inline/Cargo.toml
css-inline/src/lib.rs
css-inline/tests/test_inlining.rs

fix: Invalid handling of double-quoted property values

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/python/src/lib.rs
bindings/python/tests-py/test_inlining.py
css-inline/src/error.rs
css-inline/src/lib.rs
css-inline/tests/test_inlining.rs

chore: Separate `InlineError::MissingStyleSheet` error variant

---

css-inline/src/lib.rs

Fixes #152. I've never coded in Rust before, so this likely needs some touch up/further testing.

Support !important rule

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/wasm/CHANGELOG.md
css-inline/src/lib.rs
css-inline/tests/test_inlining.rs

fix: Ignoring selectors' specificity when applying declarations from different qualified rules

---

CHANGELOG.md
README.md
bindings/python/CHANGELOG.md
bindings/python/README.md
bindings/python/tests-py/external.css
bindings/python/tests-py/test_inlining.py
bindings/wasm/CHANGELOG.md
css-inline/src/lib.rs
css-inline/tests/test_inlining.rs

feat: Support for the `file://` URI scheme in `base_url`

---

bindings/python/CHANGELOG.md
bindings/python/css_inline.pyi

chore(python): Distribute typing information

---

css-inline/tests/test_inlining.rs

test: Add extra test for complex child selectors

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/ruby/CHANGELOG.md
bindings/wasm/CHANGELOG.md
css-inline/src/html/document.rs
css-inline/src/html/iter.rs
css-inline/src/html/node.rs

perf: Simplify iteration over nodes

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/ruby/CHANGELOG.md
bindings/wasm/CHANGELOG.md
css-inline/src/html/attributes.rs
css-inline/src/html/document.rs
css-inline/src/html/node.rs
css-inline/src/html/serializer.rs
css-inline/src/lib.rs

perf: Move inlining to the serialization phase

---

CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/ruby/CHANGELOG.md
bindings/wasm/CHANGELOG.md
css-inline/src/html/serializer.rs
css-inline/tests/test_inlining.rs

fix: Applying new styles only to the first matching tag during styles merging

---

.github/workflows/build.yml
CHANGELOG.md
README.md
bindings/python/CHANGELOG.md
bindings/python/Cargo.toml
bindings/python/README.md
bindings/ruby/CHANGELOG.md
bindings/ruby/css_inline.gemspec
bindings/ruby/ext/css_inline/Cargo.toml
bindings/wasm/CHANGELOG.md
bindings/wasm/Cargo.toml
bindings/wasm/src/lib.rs
css-inline/Cargo.toml
css-inline/src/hasher.rs
css-inline/src/html/document.rs
css-inline/src/html/element.rs
css-inline/src/html/selectors/mod.rs
css-inline/src/html/selectors/selector_impl.rs
css-inline/src/html/serializer.rs
css-inline/src/lib.rs
css-inline/src/parser.rs

chore: Update `cssparser` & `selectors`

---

CHANGELOG.md
bindings/javascript/CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/ruby/CHANGELOG.md
css-inline/src/html/element.rs
css-inline/tests/test_inlining.rs

fix: Nth-child selector

---

CHANGELOG.md
README.md
bindings/c/CHANGELOG.md
bindings/c/README.md
bindings/javascript/CHANGELOG.md
bindings/javascript/README.md
bindings/python/CHANGELOG.md
bindings/python/README.md
bindings/ruby/CHANGELOG.md
bindings/ruby/README.md
css-inline/src/html/serializer.rs
css-inline/tests/test_inlining.rs

feat: Support the data-css-inline=keep attribute

---

.github/workflows/build.yml
.github/workflows/javascript-release.yml
bindings/javascript/CHANGELOG.md
bindings/javascript/npm/android-arm-eabi/README.md
bindings/javascript/npm/android-arm-eabi/package.json
bindings/javascript/npm/android-arm64/README.md
bindings/javascript/npm/android-arm64/package.json
bindings/javascript/npm/darwin-arm64/README.md
bindings/javascript/npm/darwin-x64/README.md
bindings/javascript/npm/linux-arm-gnueabihf/README.md
bindings/javascript/npm/linux-arm64-gnu/README.md
bindings/javascript/npm/linux-arm64-musl/README.md
bindings/javascript/npm/linux-x64-gnu/README.md
bindings/javascript/npm/linux-x64-musl/README.md
bindings/javascript/npm/win32-x64-msvc/README.md
bindings/javascript/package.json

chore(js): Add packages for aarch64-linux-android and arm-linux-androideabi

---

CHANGELOG.md
bindings/c/CHANGELOG.md
bindings/javascript/CHANGELOG.md
bindings/python/CHANGELOG.md
bindings/ruby/CHANGELOG.md
css-inline/src/html/serializer.rs
css-inline/tests/test_inlining.rs

fix: Precedence of element styles over other styles

---

CHANGELOG.md
css-inline/src/main.rs
css-inline/tests/extra.css
css-inline/tests/test_cli.rs

feat(cli): `--extra-css-file` option to load additional CSS from files
